### ISSUE TITLE
how to auto get EC2's public IP 

### ISSUE THREAD

**Issue by davincizhao** [udacity/nd9991-c3-hello-world-exercise-solution#1]
in main4.yml
after creating infrastructure ec2, need to use ansible to do some config tasks in this EC2.
how to auto get EC2's public IP?
Now it seems to need to manually get and edit the main4.yml file?
any other solution?
  # Use the public IP if the VM is already created
  hosts: 44.192.7.133

**Comment by SudKul** [comment]
Hi @davincizhao 
_how to auto get EC2's public IP?_
See the details of the individual EC2 instance in your AWS console - https://console.aws.amazon.com/ec2/v2/home 

_Now it seems to need to manually get and edit the main4.yml file?_
Yes, once you have your EC2 instance's public IP, then you can enter it into the main playbook file or the inventory file.
